# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 14:19
from __future__ import unicode_literals

import DjangoUeditor.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name=b'\xe6\x96\x87\xe7\xab\xa0\xe6\xa0\x87\xe9\xa2\x98')),
                ('slug', models.CharField(max_length=255, verbose_name=b'\xe6\x96\x87\xe7\xab\xa0\xe7\xbd\x91\xe5\x9d\x80')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default=b'', verbose_name=b'\xe6\x96\x87\xe7\xab\xa0\xe5\x86\x85\xe5\xae\xb9')),
                ('published', models.BooleanField(default=True, verbose_name=b'\xe6\xad\xa3\xe5\xbc\x8f\xe5\x8f\x91\xe5\xb8\x83')),
                ('pub_date', models.DateTimeField(default=b'2017-01-16 22:19:58', verbose_name=b'\xe5\x8f\x91\xe5\xb8\x83\xe6\x97\xb6\xe9\x97\xb4')),
                ('update_time', models.DateTimeField(default=b'2017-01-16 22:19:58', verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'\xe4\xbd\x9c\xe8\x80\x85')),
            ],
            options={
                'verbose_name': '\u6587\u7ae0',
                'verbose_name_plural': '\u6587\u7ae0',
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name=b'\xe6\xa0\x8f\xe7\x9b\xae\xe5\x90\x8d\xe7\xa7\xb0')),
                ('slug', models.CharField(max_length=255, verbose_name=b'\xe6\xa0\x8f\xe7\x9b\xae\xe7\xbd\x91\xe5\x9d\x80')),
                ('intro', models.TextField(default=b'', verbose_name=b'\xe6\xa0\x8f\xe7\x9b\xae\xe7\xae\x80\xe4\xbb\x8b')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': '\u680f\u76ee',
                'verbose_name_plural': '\u680f\u76ee',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='column',
            field=models.ManyToManyField(to='CMScore.Column', verbose_name=b'\xe6\x89\x80\xe5\xb1\x9e\xe6\xa0\x8f\xe7\x9b\xae'),
        ),
    ]
