# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMScore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default='2017-01-16 01:12:45', verbose_name='发布时间'),
        ),
        migrations.AddField(
            model_name='article',
            name='update_time',
            field=models.DateTimeField(default='2017-01-16 01:12:45', verbose_name='更新时间'),
        ),
    ]
