# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CMScore', '0003_auto_20170116_2304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ['sort'], 'verbose_name': '\u680f\u76ee', 'verbose_name_plural': '\u680f\u76ee'},
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'\xe5\x8f\x91\xe5\xb8\x83\xe6\x97\xb6\xe9\x97\xb4'),
        ),
        migrations.AlterField(
            model_name='article',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4'),
        ),
    ]
