# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 04:28
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMScore', '0003_auto_20170116_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default='2017-01-16 12:28:53', verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='update_time',
            field=models.DateTimeField(default='2017-01-16 12:28:53', verbose_name='更新时间'),
        ),
    ]
