# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMScore', '0006_auto_20170116_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='sort',
            field=models.IntegerField(default=100, verbose_name=b'\xe6\x8e\x92\xe5\xba\x8f'),
        ),
    ]
